.\"Modified from man(1) of FreeBSD, the NetBSD mdoc.template, and mdoc.samples.
.Dd 30/6/24               \" d/m/y
.Dt cmake-template 1
.Os Darwin
.Sh NAME
.Nm cmake-template
.Nd Generate a cmake base project
.Sh SYNOPSIS
.Nm
.Ar name
.Sh DESCRIPTION
.Bl -tag -width -indent
.It name
project name
.El
.Sh SEE ALSO
README.md